import type { Schema, Table } from "./schema.js";

export function formatJson(schema: Schema): string {
	return JSON.stringify(schema, null, 2);
}

interface FormatSqlOptions {
	normalizeDefaults?: boolean;
}

export function formatSql(
	schema: Schema,
	options: FormatSqlOptions = {},
): string {
	const lines: string[] = [];

	lines.push(`-- Schema generated by turso-introspect`);
	lines.push(`-- Database: ${schema.metadata.database}`);
	lines.push(`-- Timestamp: ${schema.metadata.timestamp}`);
	lines.push("");

	// Topological sort for tables
	const sortedTables = sortTablesTopologically(schema.tables);

	// 1. Tables
	for (const table of sortedTables) {
		lines.push(`-- Table: ${table.name}`);

		if (isVirtualTableSql(table.sql)) {
			lines.push("-- Virtual table (not emitted as executable SQL):");
			lines.push(commentOutSql(table.sql));
			lines.push("");
			continue;
		}

		const tableSql = options.normalizeDefaults
			? normalizeDefaultExpressions(table.sql)
			: table.sql;

		lines.push(`${tableSql};`);
		lines.push("");

		// Indexes
		// sqlite_master table SQL does NOT include external indexes (created with CREATE INDEX).
		// It only includes inline constraints (PRIMARY KEY, UNIQUE).
		// So we iterate over indexes and output the ones that have their own SQL.
		for (const idx of table.indexes) {
			if (idx.origin === "c" && idx.sql) {
				const indexSql = options.normalizeDefaults
					? normalizeDefaultExpressions(idx.sql)
					: idx.sql;
				lines.push(`${indexSql};`);
			}
		}
		lines.push("");
	}

	// 2. Views
	for (const view of schema.views) {
		lines.push(`-- View: ${view.name}`);
		lines.push(`${view.sql};`);
		lines.push("");
	}

	// 3. Triggers
	for (const trigger of schema.triggers) {
		lines.push(`-- Trigger: ${trigger.name}`);
		lines.push(`${trigger.sql};`);
		lines.push("");
	}

	return lines.join("\n");
}

function sortTablesTopologically(tables: Table[]): Table[] {
	const tableMap = new Map(tables.map((t) => [t.name, t]));
	const visited = new Set<string>();
	const visiting = new Set<string>(); // for cycle detection
	const sorted: Table[] = [];

	function visit(tableName: string) {
		if (visited.has(tableName)) return;
		if (visiting.has(tableName)) {
			// Cycle detected. We just break the cycle here and proceed.
			// In a real circular dependency, SQLite allows it if we defer FK checks, but for creation order, we just have to pick one.
			return;
		}

		visiting.add(tableName);

		const table = tableMap.get(tableName);
		if (table) {
			for (const fk of table.foreignKeys) {
				// Dependency: 'table' depends on 'fk.table'
				if (fk.table !== tableName && tableMap.has(fk.table)) {
					visit(fk.table);
				}
			}
		}

		visiting.delete(tableName);
		visited.add(tableName);
		if (table) sorted.push(table);
	}

	for (const table of tables) {
		visit(table.name);
	}

	return sorted;
}

function isVirtualTableSql(sql: string): boolean {
	return /^\s*CREATE\s+VIRTUAL\s+TABLE\b/i.test(sql);
}

function commentOutSql(sql: string): string {
	return sql
		.split("\n")
		.map((line) => `-- ${line}`)
		.join("\n");
}

function normalizeDefaultExpressions(sql: string): string {
	return sql.replace(
		/\bDEFAULT\s+(?:\(\s*)?(current_timestamp|current_date|current_time)(?:\s*\))?/gi,
		(_, keyword: string) => `DEFAULT ${keyword.toUpperCase()}`,
	);
}
