import type { Schema } from "./schema.js";

const TYPESCRIPT_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function sqliteTypeToTs(declaredType: string): string {
	const type = declaredType.toUpperCase();

	if (type.includes("INT")) return "number";
	if (type.includes("CHAR") || type.includes("CLOB") || type.includes("TEXT")) {
		return "string";
	}
	if (type.includes("BLOB") || type === "") return "Uint8Array";
	if (type.includes("REAL") || type.includes("FLOA") || type.includes("DOUB")) {
		return "number";
	}

	return "number | string";
}

export function toInterfaceName(tableName: string): string {
	const name = tableName
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean)
		.map((part) => {
			const normalizedPart = part.toLowerCase();
			return `${normalizedPart[0]?.toUpperCase()}${normalizedPart.slice(1)}`;
		})
		.join("");

	if (name.length === 0) return "Table";
	return /^\d/.test(name) ? `T${name}` : name;
}

function formatPropertyName(name: string): string {
	return TYPESCRIPT_IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

function createInterfaceNames(tableNames: string[]): Map<string, string> {
	const usedNames = new Set(["Tables", "Uint8Array"]);
	const interfaceNames = new Map<string, string>();

	for (const tableName of tableNames) {
		const baseName = toInterfaceName(tableName);
		let interfaceName = baseName;

		if (usedNames.has(interfaceName)) {
			interfaceName = `${baseName}Row`;
			let suffix = 2;
			while (usedNames.has(interfaceName)) {
				interfaceName = `${baseName}Row${suffix}`;
				suffix += 1;
			}
		}

		usedNames.add(interfaceName);
		interfaceNames.set(tableName, interfaceName);
	}

	return interfaceNames;
}

function isVirtualTableSql(sql: string): boolean {
	return /^\s*CREATE\s+VIRTUAL\s+TABLE\b/i.test(sql);
}

export function formatTypescript(schema: Schema): string {
	const lines: string[] = [];
	const interfaceNames = createInterfaceNames(
		schema.tables.map((table) => table.name),
	);

	lines.push("// Generated by turso-introspect");
	lines.push(`// Database: ${schema.metadata.database}`);
	lines.push(`// Timestamp: ${schema.metadata.timestamp}`);
	lines.push(
		"// Note: columns declared PRIMARY KEY are emitted as non-nullable.",
	);
	lines.push("");

	for (const table of schema.tables) {
		const virtualComment = isVirtualTableSql(table.sql)
			? " // virtual table (FTS5/R-tree)"
			: "";
		lines.push(
			`export interface ${interfaceNames.get(table.name)} {${virtualComment}`,
		);
		for (const column of table.columns) {
			const nullable = column.notnull === 0 && column.pk === 0 ? " | null" : "";
			lines.push(
				`\t${formatPropertyName(column.name)}: ${sqliteTypeToTs(column.type)}${nullable};`,
			);
		}
		lines.push("}");
		lines.push("");
	}

	lines.push("export interface Tables {");
	for (const table of schema.tables) {
		lines.push(
			`\t${formatPropertyName(table.name)}: ${interfaceNames.get(table.name)};`,
		);
	}
	lines.push("}");

	return lines.join("\n");
}
