import { describe, expect, test } from "bun:test";
import { stripGeneratedHeader } from "./diff.js";

describe("stripGeneratedHeader", () => {
	test("removes the generated header, leaving the body intact", () => {
		const sql = [
			"-- Schema generated by turso-introspect",
			"-- Database: mydb",
			"-- Timestamp: 2026-01-01T00:00:00.000Z",
			"",
			"CREATE TABLE users (id INTEGER PRIMARY KEY);",
		].join("\n");

		const result = stripGeneratedHeader(sql);

		expect(result.split("\n")[0]).toBe(
			"CREATE TABLE users (id INTEGER PRIMARY KEY);",
		);
		expect(result).not.toContain("Schema generated by turso-introspect");
		expect(result).not.toContain("-- Database:");
		expect(result).not.toContain("-- Timestamp:");
	});

	test("returns input unchanged when there is no header", () => {
		const sql = "CREATE TABLE users (id INTEGER PRIMARY KEY);";

		expect(stripGeneratedHeader(sql)).toBe(sql);
	});

	test("returns an empty string when the input is only a header", () => {
		const sql = [
			"-- Schema generated by turso-introspect",
			"-- Database: mydb",
			"-- Timestamp: 2026-01-01T00:00:00.000Z",
			"",
		].join("\n");

		expect(stripGeneratedHeader(sql)).toBe("");
	});

	test("preserves a -- Database: line that appears mid-body", () => {
		const sql = [
			"-- Schema generated by turso-introspect",
			"-- Database: mydb",
			"-- Timestamp: 2026-01-01T00:00:00.000Z",
			"",
			"CREATE TABLE logs (id INTEGER PRIMARY KEY);",
			"-- Database: not-a-header-here",
		].join("\n");

		const result = stripGeneratedHeader(sql);

		expect(result).toContain("-- Database: not-a-header-here");
		expect(result.split("\n")[0]).toBe(
			"CREATE TABLE logs (id INTEGER PRIMARY KEY);",
		);
	});

	test("strips differing header metadata so two schemas compare equal", () => {
		const a = [
			"-- Schema generated by turso-introspect",
			"-- Database: db-one",
			"-- Timestamp: 2026-01-01T00:00:00.000Z",
			"",
			"CREATE TABLE users (id INTEGER PRIMARY KEY);",
		].join("\n");
		const b = [
			"-- Schema generated by turso-introspect",
			"-- Database: db-two",
			"-- Timestamp: 2026-07-09T12:34:56.000Z",
			"",
			"CREATE TABLE users (id INTEGER PRIMARY KEY);",
		].join("\n");

		expect(stripGeneratedHeader(a)).toBe(stripGeneratedHeader(b));
	});
});
